version: '3.8'

services:
  db:
    image: postgres:14
    container_name: gym_app
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: gym_crm
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - gym_network


networks:
  gym_network:
    driver: bridge

volumes:
  postgres_data:
