spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5435/gym_crm_prod
    username: postgres
    password: postgres

  flyway:
    url: jdbc:postgresql://localhost:5435/gym_crm_prod
    user: postgres
    password: postgres
logging:
  pattern:
    console: "%d{yyyy-MM-dd'T'HH:mm:ss.SSSXXX} [%thread] [%X{transactionId}] %-5level %logger{36} - %msg%n"
  level:
    root: info