spring:
  activemq:
#    broker-url: tcp://activemq:61616
#    user: admin
#    password: admin
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
  h2:
    console:
      enabled: true
  flyway:
    enabled: true
    locations: classpath:db/migration
    schemas: ${DB_SCHEMA:public}
    table: flyway_schema_history
    baseline-on-migrate: false
    placeholders:
      schema: ${DB_SCHEMA:public}
    validate-on-migrate: true
    clean-disabled: true
  main:
    allow-bean-definition-overriding: true
  application:
    name: GymCRM
  jwt:
    secret: ${JWT_SECRET}
management:
  endpoints:
    web:
      exposure:
        include: [ ]
  prometheus:
    metrics:
      export:
        enabled: true
  endpoint:
    health:
      show-details: "ALWAYS"
springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    path: /swagger-ui.html
logging:
  pattern:
    console: "%d{yyyy-MM-dd'T'HH:mm:ss.SSSXXX} [%thread] [%X{transactionId}] %-5level %logger{36} - %msg%n"
  level:
    level:
    root: info
    org.hibernate.orm.jdbc.bind: trace

user:
  password:
    length: 12
    characters: "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789!@#$%^&*()"

