spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://postgres:5432/gym_crm_local
    username: postgres
    password: postgres
  flyway:
    url: ${spring.datasource.url}
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}
eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-server:8761/eureka/
  instance:
    preferIpAddress: true
resilience4j:
  circuitbreaker:
    instances:
      trainerWorkloadService:
        failure-rate-threshold: 70
        slow-call-rate-threshold: 70
        slow-call-duration-threshold: 3000
        minimum-number-of-calls: 3
        sliding-window-size: 5
        permitted-number-of-calls-in-half-open-state: 1
        wait-duration-in-open-state: 2000
logging:
  level:
      root: info