spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://postgres:5432/gym_crm_prod
    username: postgres
    password: postgres
  flyway:
    url: ${spring.datasource.url}
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}
eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-server:8761/eureka/
  instance:
    preferIpAddress: true
resilience4j:
  circuitbreaker:
    instances:
      trainerWorkloadService:
        failure-rate-threshold: 40
        slow-call-rate-threshold: 40
        slow-call-duration-threshold: 1500
        minimum-number-of-calls: 10
        sliding-window-size: 20
        permitted-number-of-calls-in-half-open-state: 5
        wait-duration-in-open-state: 10000
logging:
  pattern:
    console: "%d{yyyy-MM-dd'T'HH:mm:ss.SSSXXX} [%thread] [%X{transactionId}] %-5level %logger{36} - %msg%n"
  level:
    root: info