spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/gym_crm_local
    username: postgres
    password: postgres

  flyway:
    url: jdbc:postgresql://localhost:5432/gym_crm_local
    user: postgres
    password: postgres
logging:
  level:
      root: debug