-- Create Users Table
CREATE TABLE IF NOT EXISTS users (
                       id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                       first_name VARCHAR(255) NOT NULL,
                       last_name VARCHAR(255) NOT NULL,
                       username VARCHAR(255) NOT NULL,
                       password VARCHAR(255) NOT NULL,
                       is_active BOOLEAN NOT NULL
);

-- Create Training Types Table
CREATE TABLE IF NOT EXISTS training_types (
                                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                training_type_name VARCHAR(255) NOT NULL
);

-- Create Trainers Table
CREATE TABLE IF NOT EXISTS trainer (
                         id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                         specialization_id BIGINT,
                         user_id BIGINT UNIQUE NOT NULL,
                         FOREIGN KEY (specialization_id) REFERENCES training_types(id),
                         FOREIGN KEY (user_id) REFERENCES users(id)
);

-- Create Trainees Table
CREATE TABLE IF NOT EXISTS trainee (
                         id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                         date_of_birth TIMESTAMP,
                         address VARCHAR(255),
                         user_id BIGINT UNIQUE,
                         FOREIGN KEY (user_id) REFERENCES users(id)
);

-- Create Training Table
CREATE TABLE IF NOT EXISTS training (
                          id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                          trainee_id BIGINT,
                          trainer_id BIGINT,
                          training_name VARCHAR(255) NOT NULL,
                          training_type_id BIGINT,
                          training_date TIMESTAMP,
                          training_duration INT NOT NULL,
                          FOREIGN KEY (trainee_id) REFERENCES trainee(id),
                          FOREIGN KEY (trainer_id) REFERENCES trainer(id),
                          FOREIGN KEY (training_type_id) REFERENCES training_types(id)
);
